services:
  api:
    build: .
    container_name: url_shortener
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - cassandra
    networks:
      - urlnet

  redis:
    image: redis:7
    container_name: redis_cache
    restart: always
    volumes:
      - redis-data:/data
    networks:
      - urlnet

  cassandra:
    image: cassandra:4.1
    container_name: cassandra_db
    restart: always
    environment:
      - CASSANDRA_CLUSTER_NAME=${CASSANDRA_CLUSTER_NAME}
      - CASSANDRA_DC=${CASSANDRA_LOCAL_DATACENTER}
      - CASSANDRA_AUTHENTICATOR=${CASSANDRA_AUTHENTICATOR}
      - CASSANDRA_USER=${CASSANDRA_USER}
      - CASSANDRA_PASSWORD=${CASSANDRA_PASSWORD}
    ports:
      - "9042:9042"
    networks:
      - urlnet

volumes:
  redis-data:

networks:
  urlnet:
    driver: bridge
