services:
  api:
    build: .
    container_name: url_shortener
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      migrate:
       condition: service_completed_successfully
      redis:
       condition: service_started
    networks:
      - urlnet

  redis:
    image: redis:7
    container_name: redis_cache
    restart: always
    volumes:
      - redis-data:/data
    networks:
      - urlnet

  cassandra:
    image: cassandra:4.1
    container_name: cassandra_db
    restart: always
    environment:
      - CASSANDRA_CLUSTER_NAME=${CASSANDRA_CLUSTER_NAME}
      - CASSANDRA_DC=${CASSANDRA_LOCAL_DATACENTER}
      - CASSANDRA_AUTHENTICATOR=${CASSANDRA_AUTHENTICATOR}
      - CASSANDRA_USER=${CASSANDRA_USER}
      - CASSANDRA_PASSWORD=${CASSANDRA_PASSWORD}
    ports:
      - "9042:9042"
    healthcheck:
      test: ["CMD-SHELL", "cqlsh localhost 9042 -e 'DESCRIBE KEYSPACES'"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - urlnet

  migrate:
    build: .
    command: npm run migrate
    env_file:
      - .env
    depends_on:
      cassandra:
        condition: service_healthy
    networks:
      - urlnet

volumes:
  redis-data:

networks:
  urlnet:
    driver: bridge
